
#include "test.h"

int		main(void)
{
	int				test;
	char			*s = "Here";
	char			*val = "123456789ABCDEFGHIJK"; //20 length string, not counting null
	int				t;
	g_pass 			= 0;
	g_test			= 0;

	printf("\n____________________________________\nSTRINGS: \n\n");

	printf(				"%%s");
	test = printf(				"		|%s|\n", "");
	t = ft_printf(				"		|%s|\n", "");
	result(test, t);
	printf(				"%%ss");
	test = printf(				"		|%ss|\n", s);
	t = ft_printf(				"		|%ss|\n", s);
	result(test, t);
	printf(				"%%3s");
	test = printf(				"		|%5s|\n", s);
	t = ft_printf(				"		|%5s|\n", s);
	result(test, t);
	printf(				"%%5s");
	test = printf(				"		|%5s|\n", s);
	t = ft_printf(				"		|%5s|\n", s);
	result(test, t);
	printf(				"%%11s");
	test = printf(				"		|%11s|\n", s);
	t = ft_printf(				"		|%11s|\n", s);
	result(test, t);
	printf(				"%%s%%s");
	test = printf(				"		|%s%s|\n", s, "ok");
	t = ft_printf(				"		|%s%s|\n", s, "ok");
	result(test, t);
	printf(				"%%-5s");
	test = printf(				"		|%-5s|\n", s);
	t = ft_printf(				"		|%-5s|\n", s);
	result(test, t);
	printf(				"%%.2s");
	test = printf(				"		|%.2s|\n", s);
	t = ft_printf(				"		|%.2s|\n", s);
	result(test, t);
	printf(				"%%*s,6");
	test = printf(				"		|%*s|\n", 6, s);
	t = ft_printf(				"		|%*s|\n", 6, s);
	result(test, t);
	printf(				"%%6.4s");
	test = printf(				"		|%6.4s|\n", s);
	t = ft_printf(				"		|%6.4s|\n", s);
	result(test, t);
	printf(				"%%*.*s");
	test = printf(				"		|%*.*s|\n", -5, 2, s);
	t = ft_printf(				"		|%*.*s|\n", -5, 2, s);
	result(test, t);
	printf(				"%%*s,-1");
	test = printf(				"		|%*s|\n", -1, s);
	t = ft_printf(				"		|%*s|\n", -1, s);
	result(test, t);
	printf(				"%%*s");
	test = printf(				"		|%*s|\n", 0, s);
	t = ft_printf(				"		|%*s|\n", 0, s);
	result(test, t);
	printf(				"%%-*s,5");
	test = printf(				"		|%-*s|\n", 5, s);
	t = ft_printf(				"		|%-*s|\n", 5, s);
	result(test, t);
	printf(				"%%--*s,1");
	test = printf(				"		|%--*s|\n", 1, s);
	t = ft_printf(				"		|%--*s|\n", 1, s);
	result(test, t);
	printf(				"%%.*s,2");
	test = printf(				"		|%.*s|\n", 2, s);
	t = ft_printf(				"		|%.*s|\n", 2, s);
	result(test, t);
	printf(				"%%-6.4s");
	test = printf(				"		|%-6.4s|\n", s);
	t = ft_printf(				"		|%-6.4s|\n", s);
	result(test, t);
	printf(				"%%05s");
	test =	printf(				"		|%09s|\n", s);
	t =	ft_printf(				"		|%09s|\n", s);
	result(test, t);
	printf(				"%%0-0s");
	test =	printf(				"		|%0-0s|\n", s);
	t =	ft_printf(				"		|%0-0s|\n", s);
	result(test, t);
	printf("\n	[Above: %d | %d OK]\n", g_test, g_pass);
printf("\n_____________________________________\nNULL: \n\n");
	printf(				"%%s,NULL");
	test = printf(				"		|%s|\n", NULL);
	t = ft_printf(				"		|%s|\n", NULL);
	result(test, t);
	printf(				"%%011s");
	test = printf(				"		|%011s|\n", NULL);
	t = ft_printf(				"		|%011s|\n", NULL);
	result(test, t);
	printf(				"%%-0.8s");
	test = printf(				"		|%-0.8s|\n", NULL);
	t = ft_printf(				"		|%-0.8s|\n", NULL);
	result(test, t);
	printf(				"%%-5s");
	test = printf(				"		|%-5s|\n", NULL);
	t = ft_printf(				"		|%-5s|\n", NULL);
	result(test, t);
	printf(				"after\\0");
	test = printf(				"		|%s|\n", "this is ok\0but this one should be hidden");
	t = ft_printf(				"		|%s|\n", "this is ok\0but this one should be hidden");
	result(test, t);
	printf(				"%%.*s,0");
	test = printf(				"		|%.*s|\n", 0, s);
	t = ft_printf(				"		|%.*s|\n", 0, s);
	result(test, t);
	printf(				"**-7-3");
	test = printf(				"		|%*.*s|\n", -7, -3, "yolo");
	t = ft_printf(				"		|%*.*s|\n", -7, -3, "yolo");
	result(test, t);
	printf(				".*-3");
	test = printf(				"		|%.*s|\n", -3, "hello");
	t = ft_printf(				"		|%.*s|\n", -3, "hello");
	result(test, t);
	printf("\n	[Above: %d | %d OK]\n", g_test, g_pass);
printf("\n_____________________________________\nUN.BEHAVIOR: \n\n");
	printf(				"%%011s");
	test = printf(				"		|%011s|\n", s);
	t = ft_printf(				"		|%011s|\n", s);
	result(test, t);
	printf(				"%%0-5s");
	test = printf(				"		|%0-5s|\n", s);
	t = ft_printf(				"		|%0-5s|\n", s);
	result(test, t);
	test = printf(			"-0*0: |%-0*s|\n", 0, val);
	t = ft_printf(			"-0*0: |%-0*s|\n", 0, val);
	result(test, t);
	test = printf(			"-0*3: |%-0*s|\n", 3, val);
	t = ft_printf(			"-0*3: |%-0*s|\n", 3, val);
	result(test, t);
	test = printf(			"-0*0: |%-0*s|\n", 0, NULL);
	t = ft_printf(			"-0*0: |%-0*s|\n", 0, NULL);
	result(test, t);
	test = printf(			"-0*3: |%-0*s|\n", 3, NULL);
	t = ft_printf(			"-0*3: |%-0*s|\n", 3, NULL);
	result(test, t);
	printf("\n_____________________________________\nstrings \n");

	printf("\n[RESULT: \x1b[33m%d\x1b[0m correct out of \x1b[33m%d\x1b[0m tests]\n\n", g_pass, g_test);

	return (0);
}
