
#include "test.h"

int		main(void)
{
	int				test;
	int				r = 0;
	unsigned int	i = -7;
	int				d = 55;
	char			c = 'c';
	char			*s = "Here";
	int				t;
	int				p = &t;
	g_pass 			= 0;
	g_test			= 0;

printf("____________________________________\nPOINTER: \n\n");
	
		printf(			"arg 1");
	test =	printf(			" 	|%p|\n", 1);
	t =	ft_printf(			" 	|%p|\n", 1);
	result(test, t);
		printf(			"arg -1");
	test =	printf(			" 	|%p|\n", -1);
	t =	ft_printf(			" 	|%p|\n", -1);
	result(test, t);
		printf(			"no arg");
	test =	printf(			" 	|%p|\n");
	t =	ft_printf(			" 	|%p|\n");
	result(test, t);
		printf(			"&c");
	test =	printf(			" 	|%p|\n", &c);
	t =	ft_printf(			" 	|%p|\n", &c);
	result(test, t);
		printf(			"&s");
	test =	printf(			" 	|%p|\n", &s);
	t =	ft_printf(			" 	|%p|\n", &s);
	result(test, t);
		printf(			"&d");
	test =	printf(			" 	|%p|\n", &d);
	t =	ft_printf(			" 	|%p|\n", &d);
	result(test, t);
		printf(			"&15c");
	test =	printf(			" 	|%15p|\n", &c);
	t =	ft_printf(			" 	|%15p|\n", &c);
	result(test, t);
		printf(			"15.20");
	test =	printf(			" 	|%15.20p|\n", &s);
	t =	ft_printf(			" 	|%15.20p|\n", &s);
	result(test, t);

printf("_____________________________________\nZERO: \n\n");
	
		printf(			"p,0");
	test =	printf(			"		|%p|\n", 0);
	t =	ft_printf(			"		|%p|\n", 0);
	result(test, t);
		printf(			".0p");
	test =	printf(			"		|%.0p|\n", 0);
	t =	ft_printf(			"		|%.0p|\n", 0);
	result(test, t);
		printf(			"0p");
	test =	printf(			"		|%0p|\n", 0);
	t =	ft_printf(			"		|%0p|\n", 0);
	result(test, t);
		printf(			"-p");
	test =	printf(			"		|%-p|\n", 0);
	t =	ft_printf(			"		|%-p|\n", 0);
	result(test, t);
		printf(			" p");
	test =	printf(			"		|% p|\n", 0);
	t =	ft_printf(			"		|% p|\n", 0);
	result(test, t);
		printf(			"+p");
	test =	printf(			"		|%+p|\n", 0);
	t =	ft_printf(			"		|%+p|\n", 0);
	result(test, t);
		printf(			"10p");
	test =	printf(			"		|%10p|\n", 0);
	t =	ft_printf(			"		|%10p|\n", 0);
	result(test, t);
		printf(			"-10p");
	test =	printf(			"		|%-10p|\n", 0);
	t =	ft_printf(			"		|%-10p|\n", 0);
	result(test, t);
		printf(			"010p");
	test =	printf(			"		|%010p|\n", 0);
	t =	ft_printf(			"		|%010p|\n", 0);
	result(test, t);
		printf(			"-10.p");
	test =	printf(			"		|%-10.p|\n", 0);
	t =	ft_printf(			"		|%-10.p|\n", 0);
	result(test, t);
		printf(			"10.p");
	test =	printf(			"		|%10.p|\n", 0);
	t =	ft_printf(			"		|%10.p|\n", 0);
	result(test, t);
		printf(			"010.p");
	test =	printf(			"		|%010.p|\n", 0);
	t =	ft_printf(			"		|%010.p|\n", 0);
	result(test, t);
		printf(			"0.p");
	test =	printf(			"		|%0.p|\n", 0);
	t =	ft_printf(			"		|%0.p|\n", 0);
	result(test, t);
		printf(			".p");
	test =	printf(			"		|%.p|\n", 0);
	t =	ft_printf(			"		|%.p|\n", 0);
	result(test, t);
		printf(			".0p");
	test =	printf(			"		|%.0p|\n", 0);
	t =	ft_printf(			"		|%.0p|\n", 0);
	result(test, t);
		printf(			".5p");
	test =	printf(			"		|%.5p|\n", 0);
	t =	ft_printf(			"		|%.5p|\n", 0);
	result(test, t);
		printf(			"5.2p");
	test =	printf(			"		|%9.2p|\n", 0);
	t =	ft_printf(			"		|%9.2p|\n", 0);
	result(test, t);
		printf(			"10.2p");
	test =	printf(			"		|%10.2p|\n", 0);
	t =	ft_printf(			"		|%10.2p|\n", 0);
	result(test, t);
		printf(			"2.10p");
	test =	printf(			"		|%2.10p|\n", 0);
	t =	ft_printf(			"		|%2.10p|\n", 0);
	result(test, t);

	printf("\n [Above: %d | %d OK]\n\n", g_test, g_pass);

printf("\n_____________________________________\nFLAGS: \n\n");

		printf(			"-p");
	test =	printf(			"	|%-p|\n", i);
	t =	ft_printf(			"	|%-p|\n", i);
	result(test, t);
		printf(			"0p");
	test =	printf(			"	|%0p|\n", i);
	t =	ft_printf(			"	|%0p|\n", i);
	result(test, t);
		printf(			".p");
	test =	printf(			"	|%.p|\n", i);
	t =	ft_printf(			"	|%.p|\n", i);
	result(test, t);
		printf(			".5p");
	test =	printf(			"	|%.5p|\n", i);
	t =	ft_printf(			"	|%.5p|\n", i);
	result(test, t);
		printf(			".0p");
	test =	printf(			"	|%.0p|\n", i);
	t =	ft_printf(			"	|%.0p|\n", i);
	result(test, t);
		printf(			"-11.2p");
	test =	printf(			"	|%-11.2p|\n", -1);
	t =	ft_printf(			"	|%-11.2p|\n", -1);
	result(test, t);
		printf(			"11.2p");
	test =	printf(			"	|%11.2p|\n", -1);
	t =	ft_printf(			"	|%11.2p|\n", -1);
	result(test, t);
		printf(			"2.11p");
	test =	printf(			"	|%2.11p|\n", -1);
	t =	ft_printf(			"	|%2.11p|\n", -1);
	result(test, t);
		printf(			"-15.11p");
	test =	printf(			"	|%-15.11p|\n", -1);
	t =	ft_printf(			"	|%-15.11p|\n", -1);
	result(test, t);
		printf(			"15.11p");
	test =	printf(			"	|%15.11p|\n", -1);
	t =	ft_printf(			"	|%15.11p|\n", -1);
	result(test, t);
		printf(			"11.15p");
	test =	printf(			"	|%11.15p|\n", -1);
	t =	ft_printf(			"	|%11.15p|\n", -1);
	result(test, t);
		printf(			"00.15p");
	test =	printf(			"	|%00.15p|\n", -1);
	t =	ft_printf(			"	|%00.15p|\n", -1);
	result(test, t);
		printf(			"015p");
	test =	printf(			"	|%015p|\n", -1);
	t =	ft_printf(			"	|%015p|\n", -1);
	result(test, t);
		printf(			"15p");
	test =	printf(			"	|%15p|\n", -1);
	t =	ft_printf(			"	|%15p|\n", -1);
	result(test, t);
		printf(			"-15p");
	test =	printf(			"	|%-15p|\n", -1);
	t =	ft_printf(			"	|%-15p|\n", -1);
	result(test, t);

	printf("\n [Above: %d | %d OK]\n\n", g_test, g_pass);

printf("\n_____________________________________\nNEXT LVL: \n\n");

		printf(			" p");
	test =	printf(			"	|% p|\n", i);
	t =	ft_printf(			"	|% p|\n", i);
	result(test, t);
		printf(			"+p");
	test =	printf(			"	|%+p|\n", i);
	t =	ft_printf(			"	|%+p|\n", i);
	result(test, t);
		printf(			"&int0");
	test =	printf(			"	|%p|\n", &r);
	t =	ft_printf(			"	|%p|\n", &r);
	result(test, t);

	printf("\n [Above: %d | %d OK]\n\n", g_test, g_pass);

printf("\n_____________________________________\nPERCENT: \n\n");
	
		printf(				"%%0-0%%");
	test =	printf(				"		|%0-0%|\n");
	t =	ft_printf(				"		|%0-0%|\n");
	result(test, t);
		printf(				"%%05%%");
	test =	printf(				"		|%05%|\n");
	t =	ft_printf(				"		|%05%|\n");
	result(test, t);
		printf(				"%%-5%%");
	test =	printf(				"		|%-5%|\n");
	t =	ft_printf(				"		|%-5%|\n");
	result(test, t);
		printf(				"%%-05%%");
	test =	printf(				"		|%-05%|\n");
	t =	ft_printf(				"		|%-05%|\n");
	result(test, t);
		printf(				"%%1.5%%");
	test =	printf(				"		|%1.5%|\n");
	t =	ft_printf(				"		|%1.5%|\n");
	result(test, t);
		printf(				"%%5.1%%");
	test =	printf(				"		|%5.1%|\n");
	t =	ft_printf(				"		|%5.1%|\n");
	result(test, t);
	test = printf("*8.4: 		|%*.4%|\n", 8);
	t = ft_printf("*8.4: 		|%*.4%|\n", 8);
	result(test, t);
	test = printf("*4.8: 		|%*.8%|\n", 4);
	t = ft_printf("*4.8: 		|%*.8%|\n", 4);
	result(test, t);
	test = printf("*8.8: 		|%*.8%|\n", 8);
	t = ft_printf("*8.8: 		|%*.8%|\n", 8);
	result(test, t);
	test = printf("8.*4: 		|%8.*%|\n", 4);
	t = ft_printf("8.*4: 		|%8.*%|\n", 4);
	result(test, t);
	test = printf("4.*8: 		|%4.*%|\n", 8);
	t = ft_printf("4.*8: 		|%4.*%|\n", 8);
	result(test, t);
	test = printf("8.*8: 		|%8.*%|\n", 8);
	t = ft_printf("8.*8: 		|%8.*%|\n", 8);
	result(test, t);
	test = printf("Mfw *5: 	|%*%|\n",  5);
	t = ft_printf("Mfw *5: 	|%*%|\n",  5);
	result(test, t);
	test = printf("Precis. .*i: 	|%.*%|\n", 0);
	t = ft_printf("Precis. .*i: 	|%.*%|\n", 0);
	result(test, t);
	test = printf("01.8: 		|%01.8%|\n");
	t = ft_printf("01.8: 		|%01.8%|\n");
	result(test, t);
	test = printf("Precis. .*: 	|%.*%|\n");
	t = ft_printf("Precis. .*: 	|%.*%|\n");
	result(test, t);
	test = printf("Precis. .*: 	|%.*%|\n", 0);
	t = ft_printf("Precis. .*: 	|%.*%|\n", 0);

	printf("\n\n	[Above: %d | %d OK]\n", g_test, g_pass);

	printf("\n_____________________________________\npointers \n");

	printf("\n[RESULT: \x1b[33m%d\x1b[0m correct out of \x1b[33m%d\x1b[0m tests]\n\n", g_pass, g_test);

	return (0);
}
