
#include "test.h"

int		main(void)
{
	int				test;
	unsigned int	i = -7;
	int				d = 55;
	char			c = 'c';
	char			*s = "Here";
	int				t;
	g_pass 			= 0;
	g_test			= 0;

printf("\n_____________________________________\nSRINGS: \n\n");

	printf(				"%%s+2");
	test = printf(				"		|%ss|\n", s + 2);
	t = ft_printf(				"		|%ss|\n", s + 2);
	result(test, t);

	printf("\n	[Above: %d | %d OK]\n", g_test, g_pass);

printf("_____________________________________\nDECIMALS:\n\n");
	
		printf(			"%%+d"); 		
	test =	printf(			"		|%+d|\n", i);
	t =	ft_printf(			"		|%+d|\n", i);
	result(test, t);
		printf(			"%%+7d"); 		
	test =	printf(			"		|%+5d|\n", i);
	t =	ft_printf(			"		|%+5d|\n", i);
	result(test, t);
		printf(			"%%++5d"); 		
	test =	printf(			"		|%++5d|\n", d);
	t =	ft_printf(			"		|%++5d|\n", d);
	result(test, t);
		printf(			"%%+d"); 		
	test =	printf(			"		|%+d|\n", d);
	t =	ft_printf(			"		|%+d|\n", d);
	result(test, t);
		printf(			"%%+i"); 		
	test =	printf(			"		|%+i|\n", d);
	t =	ft_printf(			"		|%+i|\n", d);
	result(test, t);
		printf(			"%%++i"); 		
	test =	printf(			"		|%++i|\n", d);
	t =	ft_printf(			"		|%++i|\n", d);
	result(test, t);
		printf(			"%%+d, 0");
	test =	printf(			"		|%+d|\n",  0);
	t =	ft_printf(			"		|%+d|\n",  0);
	result(test, t);
		printf(			"%%+d,0");
	test =	printf(			"		|%+d|\n", 0);
	t =	ft_printf(			"		|%+d|\n", 0);
	result(test, t);
		printf(			"%%+5d"); 		
	test =	printf(			"		|%+5d|\n", 0);
	t =	ft_printf(			"		|%+5d|\n", 0);
	result(test, t);
		printf(			"%%+5.d"); 		
	test =	printf(			"		|%+5.d|\n", 0);
	t =	ft_printf(			"		|%+5.d|\n", 0);
	result(test, t);
		printf(			"%%+7.5d"); 		
	test =	printf(			"		|%+7.5d|\n", 0);
	t =	ft_printf(			"		|%+7.5d|\n", 0);
	result(test, t);
		printf(			"%%+0*d"); 		
	test =	printf(			"		|%+0*d|\n", 4, 0);
	t =	ft_printf(			"		|%+0*d|\n", 4, 0);
	result(test, t);
		printf(			"%%+-*d"); 		
	test =	printf(			"		|%+0*d|\n", -4, 0);
	t =	ft_printf(			"		|%+0*d|\n", -4, 0);
	result(test, t);
		printf(			"%%+7d"); 		
	test =	printf(			"		|%+5d|\n", 55);
	t =	ft_printf(			"		|%+5d|\n", 55);
	result(test, t);
		printf(			"%%+0*d"); 		
	test =	printf(			"		|%+0*d|\n", 4, 55);
	t =	ft_printf(			"		|%+0*d|\n", 4, 55);
	result(test, t);
		printf(			"%%+-*d"); 		
	test =	printf(			"		|%+0*d|\n", -4, 55);
	t =	ft_printf(			"		|%+0*d|\n", -4, 55);
	result(test, t);
		printf(			"%% -4d");
	test =	printf(			"		|% -4d|\n", d);
	t =	ft_printf(			"		|% -4d|\n", d);
	result(test, t);
		printf(			"%%+-.d,-");
	test =	printf(			"		|%+-.d|\n", i);
	t =	ft_printf(			"		|%+-.d|\n", i);
	result(test, t);
		printf(			"%%+-8.5d");
	test =	printf(			"		|%+-8.5d|\n", i);
	t =	ft_printf(			"		|%+-8.5d|\n", i);
	result(test, t);
		printf(			"%%+-.d,0");
	test =	printf(			"		|%+-.d|\n", 0);
	t =	ft_printf(			"		|%+-.d|\n", 0);
	result(test, t);
		printf(			"%%+.d, 0");
	test =	printf(			"		|%+.d|\n", 0);
	t =	ft_printf(			"		|%+.d|\n", 0);
	result(test, t);
		printf(			"%% d, 0");
	test =	printf(			"		|% d|\n",  0);
	t =	ft_printf(			"		|% d|\n",  0);
	result(test, t);
		printf(			"%%    d"); 		
	test =	printf(			"		|%    d|\n", i);
	t =	ft_printf(			"		|%    d|\n", i);
	result(test, t);
		printf(			"%% .3d,5");
	test =	printf(			"		|% .3d|\n", 5);
	t =	ft_printf(			"		|% .3d|\n", 5);
	result(test, t);
		printf(			"%% -5d,-");
	test =	printf(			"		|% -5d|\n", i);
	t =	ft_printf(			"		|% -5d|\n", i);
	result(test, t);
		printf(			"%% -.3d");
	test =	printf(			"		|% -.3d|\n", i);
	t =	ft_printf(			"		|% -.3d|\n", i);
	result(test, t);
		printf(			"%% 4d");
	test =	printf(			"		|% 4d|\n", 0);
	t =	ft_printf(			"		|% 4d|\n", 0);
	result(test, t);
		printf(			"%% -4d");
	test =	printf(			"		|% -4d|\n", 0);
	t =	ft_printf(			"		|% -4d|\n", 0);
	result(test, t);
		printf(			"%% 04d");
	test =	printf(			"		|% 04d|\n", 0);
	t =	ft_printf(			"		|% 04d|\n", 0);
	result(test, t);
		printf(			"%% 8.5d");
	test =	printf(			"		|% 8.5d|\n", 55);
	t =	ft_printf(			"		|% 8.5d|\n", 55);
	result(test, t);
		printf(			"%%+8.5d");
	test =	printf(			"		|%+8.5d|\n", 55);
	t =	ft_printf(			"		|%+8.5d|\n", 55);
	result(test, t);
		printf(			"%%+-8.5d");
	test =	printf(			"		|%+-8.5d|\n", 55);
	t =	ft_printf(			"		|%+-8.5d|\n", 55);
	result(test, t);
		printf(			"%%+-8.5d");
	test =	printf(			"		|%+-8.5d|\n", -55);
	t =	ft_printf(			"		|%+-8.5d|\n", -55);
	result(test, t);
		printf(			"%% 0+-5d");
	test =	printf(			"		|% 0+-5d|\n", -55);
	t =	ft_printf(			"		|% 0+-5d|\n", -55);
	result(test, t);
		printf(			"%% 8.5d");
	test =	printf(			"		|% 8.5d|\n", 55);
	t =	ft_printf(			"		|% 8.5d|\n", 55);
	result(test, t);
		printf(			"%%+8.5d");
	test =	printf(			"		|%+8.5d|\n", 55);
	t =	ft_printf(			"		|%+8.5d|\n", 55);
	result(test, t);
		printf(			"%%0+8.5d");
	test =	printf(			"		|%0+8.5d|\n", i);
	t =	ft_printf(			"		|%0+8.5d|\n", i);
	result(test, t);
		printf(			"%%0+8.5d");
	test =	printf(			"		|%0+8.5d|\n", 55);
	t =	ft_printf(			"		|%0+8.5d|\n", 55);
	result(test, t);
		printf(			"%%0+8.5d");
	test =	printf(			"		|%0+8.5d|\n", 0);
	t =	ft_printf(			"		|%0+8.5d|\n", 0);
	result(test, t);
		printf(			"%%0 8.5d");
	test =	printf(			"		|%0 8.5d|\n", 0);
	t =	ft_printf(			"		|%0 8.5d|\n", 0);
	result(test, t);
		printf(			"%%+-.5d"); 		
	test =	printf(			"		|%+0*.5d|\n", -8, 55);
	t =	ft_printf(			"		|%+0*.5d|\n", -8, 55);
	result(test, t);
		printf(			"%%0+3.5d");
	test =	printf(			"		|%0+3.5d|\n", 33);
	t =	ft_printf(			"		|%0+3.5d|\n", 33);
	result(test, t);
		printf(			"%%+04d");
	test =	printf(			"		|%+04d|\n", 0);
	t =	ft_printf(			"		|%+04d|\n", 0);
	result(test, t);
		printf(			"%%+4d");
	test =	printf(			"		|%+4d|\n", 0);
	t =	ft_printf(			"		|%+4d|\n", 0);
	result(test, t);

printf("\n\n[Above: %d | %d OK]\n", g_test, g_pass);

printf("\n_____________________________________\n HEXADECIMALS: \n\n");

    printf(			"%%#9X\n");
    test =	printf(	    	"	   |%#-9X|\n", i);
	t =	ft_printf(	    	"	   |%#-9X|\n", i);
	result(test, t);
    printf(			"%%#-9X\n");
    test =	printf(	    	"	   |%#-9X|\n", i);
	t =	ft_printf(	    	"	   |%#-9X|\n", i);
	result(test, t);
    printf(			"%%#09X,-\n");
    test =	printf(	    	"	   |%#09X|\n", i);
	t =	ft_printf(	    	"	   |%#09X|\n", i);
	result(test, t);
    printf(			"%%#09X,33\n");
    test =	printf(	    	"	   |%#09X|\n", 33);
	t =	ft_printf(	    	"	   |%#09X|\n", 33);
	result(test, t);
    printf(			"%%#10.11x\n");
    test =	printf(	    	"	   |%#*.*x|\n", 10, 11, i);
	t =	ft_printf(	    	"	   |%#*.*x|\n", 10, 11, i);
	result(test, t);
		printf(			"%%#xX\n");
    test =	printf(	    	"	   |%#xX|\n", d);
	t =	ft_printf(	    	"	   |%#xX|\n", d);
	result(test, t);
		printf(			"%%#xX\n");
    test =	printf(	    	"	   |%#xX|\n", 0);
	t =	ft_printf(	    	"	   |%#xX|\n", 0);
	result(test, t);
		printf(			"%%#09X\n");
    test =	printf(	    	"	   |%#09X|\n", d);
	t =	ft_printf(	    	"	   |%#09X|\n", d);
	result(test, t);
    printf(			"%%#-9X\n");
    test =	printf(	    	"	   |%#-9X|\n", d);
	t =	ft_printf(	    	"	   |%#-9X|\n", d);
	result(test, t);
    printf(			"%%#-5.x\n");
    test =	printf(	    	"	   |%#*.x|\n", -5, d);
	t =	ft_printf(	    	"	   |%#*.x|\n", -5, d);
	result(test, t);
    printf(			"%%#8.11x\n");
    test =	printf(	    	"	   |%#*.*x|\n", 8, 11, d);
	t =	ft_printf(	    	"	   |%#*.*x|\n", 8, 11, d);
	result(test, t);
    printf(			"%%#8.2x\n");
    test =	printf(	    	"	   |%#*.*x|\n", 8, 2, d);
	t =	ft_printf(	    	"	   |%#*.*x|\n", 8, 2, d);
	result(test, t);
    printf(			"%%#8.5x\n");
    test =	printf(	    	"	   |%#*.*x|\n", 8, 5, 34);
	t =	ft_printf(	    	"	   |%#*.*x|\n", 8, 5, 34);
	result(test, t);
    printf(			"%%#8.5x\n");
    test =	printf(	    	"	   |%#*.*x|\n", 8, 5, d);
	t =	ft_printf(	    	"	   |%#*.*x|\n", 8, 5, d);
	result(test, t);
    printf(			"%%#-8.5x\n");
    test =	printf(	    	"	   |%#-*.*x|\n", 8, 5, d);
	t =	ft_printf(	    	"	   |%#-*.*x|\n", 8, 5, d);
	result(test, t);
    printf(			"%%#08.5x\n");
    test =	printf(	    	"	   |%#0*.*x|\n", 8, 5, d);
	t =	ft_printf(	    	"	   |%#0*.*x|\n", 8, 5, d);
	result(test, t);
    printf(			"%%#08.5x\n");
    test =	printf(	    	"	   |%#0*.*x|\n", 8, 5, 34);
	t =	ft_printf(	    	"	   |%#0*.*x|\n", 8, 5, 34);
	result(test, t);
    printf(			"%%#-1.1x\n");
    test =	printf(	    	"	   |%#*.*x|\n", -1, 1, d);
	t =	ft_printf(	    	"	   |%#*.*x|\n", -1, 1, d);
	result(test, t);
	printf(			"%%#10.11x\n");
    test =	printf(	    	"	   |%#*.*x|\n", 10, 11, d);
	t =	ft_printf(	    	"	   |%#*.*x|\n", 10, 11, d);
	result(test, t);
    printf(			"%%#5.1x\n");
    test =	printf(	    	"	   |%#*.*x|\n", 5, 1, d);
	t =	ft_printf(	    	"	   |%#*.*x|\n", 5, 1, d);
	result(test, t);
    printf(			"%%#011.1x\n");
    test =	printf(	    	"	   |%#0*.*x|\n", 11, 1, d);
	t =	ft_printf(	    	"	   |%#0*.*x|\n", 11, 1, d);
	result(test, t);
    printf(			"%%#0*.*x\n");
    test =	printf(	    	"	   |%#0*.*x|\n", 10, 11, d);
	t =	ft_printf(	    	"	   |%#0*.*x|\n", 10, 11, d);
	result(test, t);
	printf(			"%%+8.3d\n");
    test =	printf(	    	"	   |%+8.3d|\n", 1234);
	t =	ft_printf(	    	"	   |%+8.3d|\n", 1234);
	result(test, t);
	printf(			"%%-+8.3d\n");
    test =	printf(	    	"	   |%-+8.3d|\n", 1234);
	t =	ft_printf(	    	"	   |%-+8.3d|\n", 1234);
	result(test, t);
	printf(			"%%+-8.3d\n");
    test =	printf(	    	"	   |%+-8.3d|\n", 1234);
	t =	ft_printf(	    	"	   |%+-8.3d|\n", 1234);
	result(test, t);
	printf(			"%%0-+8.3d\n");
    test =	printf(	    	"	   |%0-+8.3d|\n", 1234);
	t =	ft_printf(	    	"	   |%0-+8.3d|\n", 1234);
	result(test, t);
	printf(			"%% 0+8.3d\n");
    test =	printf(	    	"	   |% 0+8.3d|\n", 1234);
	t =	ft_printf(	    	"	   |% 0+8.3d|\n", 1234);
	result(test, t);
	printf(			"%% $0+8.3d\n");
    test =	printf(	    	"	   |% 0+8.3d|\n", 1234);
	t =	ft_printf(	    	"	   |% 0+8.3d|\n", 1234);
	result(test, t);
	printf(			"%%4$.3d\n");
    test =	printf(	    	"	   |%4$.3d|\n", 1234);
	t =	ft_printf(	    	"	   |%4$.3d|\n", 1234);
	result(test, t);

	// printf("\n_____________________________________\nUndefined Behavior: \n\n\n");


	printf("\n_____________________________________\n Bonus: \n");
	printf("\n[RESULT: \x1b[33m%d\x1b[0m correct out of \x1b[33m%d\x1b[0m tests]", g_pass, g_test);
	if (g_pass != g_test)
		printf("\x1b[31m FAILS:\x1b[0m%d", g_test - g_pass);
	printf("\n\n");

	return (0);
}
