/* ************************************************************************** */
/*                                                                            */
/*                                                        ::::::::            */
/*   main_char.c                                        :+:    :+:            */
/*                                                     +:+                    */
/*   By: limartin <limartin@student.42.fr>            +#+                     */
/*                                                   +#+                      */
/*   Created: 2020/01/15 19:45:27 by limartin      #+#    #+#                 */
/*   Updated: 2020/06/19 21:33:08 by swofferh      ########   odam.nl         */
/*                                                                            */
/* ************************************************************************** */

#include <stdio.h>
#include "test.h"

// int		ft_printf(const char *format, ...)
// {
// 	return 0;
// }

int		main(void)
{
	char	val = '*';
	// val = '%';
	// val = 'c';
	// val = '$';
    // val = (char)-42;

	int broken = 0;
	int	bonus = 0;
	
	g_pass 	= 0;
	g_test	= 1;
	g_fail	= 0;

	int test = 0;
	int t = 0;


	test = printf(" (%d)\n", printf("Handling minimum field width"));
	t = ft_printf(" (%d)\n", ft_printf("Handling minimum field width"));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) Mfw 0: |%0c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) Mfw 0: |%0c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) Mfw 1: |%1c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) Mfw 1: |%1c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw 0: |%0c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw 0: |%0c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw 1: |%1c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw 1: |%1c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw 2: |%2c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw 2: |%2c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw 3: |%3c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw 3: |%3c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw 4: |%4c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw 4: |%4c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw 5: |%5c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw 5: |%5c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw 10: |%10c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw 10: |%10c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw 15: |%15c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw 15: |%15c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw 42: |%42c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw 42: |%42c|", val));
	result(test, t);

	test = printf(" (%d)\n", printf("Handling precision"));
	t = ft_printf(" (%d)\n", ft_printf("Handling precision"));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) Precis. 0: |%.0c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) Precis. 0: |%.0c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) Precis. 1: |%.1c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) Precis. 1: |%.1c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) Precis. 2: |%.2c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) Precis. 2: |%.2c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. 0: |%.0c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Precis. 0: |%.0c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. 1: |%.1c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Precis. 1: |%.1c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. 2: |%.2c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Precis. 2: |%.2c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. 3: |%.3c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Precis. 3: |%.3c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. 4: |%.4c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Precis. 4: |%.4c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. 5: |%.5c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Precis. 5: |%.5c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. 10: |%.10c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Precis. 10: |%.10c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. 15: |%.15c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Precis. 15: |%.15c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. 42: |%.42c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Precis. 42: |%.42c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) P .00: |%.00c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) P .00: |%.00c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) P .01: |%.01c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) P .01: |%.01c|", 0));	
	result(test, t);
	test = printf(" (%d)\n", printf("P .00: |%.00c|", val));
	t = ft_printf(" (%d)\n", ft_printf("P .00: |%.00c|", val));	
	result(test, t);
	test = printf(" (%d)\n", printf("P .01: |%.01c|", val));
	t = ft_printf(" (%d)\n", ft_printf("P .01: |%.01c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("P .02: |%.02c|", val));
	t = ft_printf(" (%d)\n", ft_printf("P .02: |%.02c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("P .03: |%.03c|", val));
	t = ft_printf(" (%d)\n", ft_printf("P .03: |%.03c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("P .04: |%.04c|", val));
	t = ft_printf(" (%d)\n", ft_printf("P .04: |%.04c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("P .05: |%.05c|", val));
	t = ft_printf(" (%d)\n", ft_printf("P .05: |%.05c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("P .010: |%.010c|", val));
	t = ft_printf(" (%d)\n", ft_printf("P .010: |%.010c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("P .015: |%.015c|", val));
	t = ft_printf(" (%d)\n", ft_printf("P .015: |%.015c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("P .042: |%.042c|", val));
	t = ft_printf(" (%d)\n", ft_printf("P .042: |%.042c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("P .007: |%.007c|", val));
	t = ft_printf(" (%d)\n", ft_printf("P .007: |%.007c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("P .000000000007: |%.000000000007c|", val));
	t = ft_printf(" (%d)\n", ft_printf("P .000000000007: |%.000000000007c|", val));
	result(test, t);

	test = printf(" (%d)\n", printf("Handling precision & minimum field width"));
	t = ft_printf(" (%d)\n", ft_printf("Handling precision & minimum field width"));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) 0.0: |%0.0c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) 0.0: |%0.0c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) 1.0: |%1.0c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) 1.0: |%1.0c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(10) 1.0: |%1.0c|", 10));
	t = ft_printf(" (%d)\n", ft_printf("(10) 1.0: |%1.0c|", 10));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) 0.1: |%0.1c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) 0.1: |%0.1c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) 1.1: |%1.1c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) 1.1: |%1.1c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("0.0: |%0.0c|", val));
	t = ft_printf(" (%d)\n", ft_printf("0.0: |%0.0c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("1.1: |%1.1c|", val));
	t = ft_printf(" (%d)\n", ft_printf("1.1: |%1.1c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("2.2: |%2.2c|", val));
	t = ft_printf(" (%d)\n", ft_printf("2.2: |%2.2c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("3.2: |%3.2c|", val));
	t = ft_printf(" (%d)\n", ft_printf("3.2: |%3.2c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("2.3: |%2.3c|", val));
	t = ft_printf(" (%d)\n", ft_printf("2.3: |%2.3c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("8.4: |%8.4c|", val));
	t = ft_printf(" (%d)\n", ft_printf("8.4: |%8.4c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("4.8: |%4.8c|", val));
	t = ft_printf(" (%d)\n", ft_printf("4.8: |%4.8c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("8.8: |%8.8c|", val));
	t = ft_printf(" (%d)\n", ft_printf("8.8: |%8.8c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("8.2: |%8.2c|", val));
	t = ft_printf(" (%d)\n", ft_printf("8.2: |%8.2c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("2.8: |%2.8c|", val));
	t = ft_printf(" (%d)\n", ft_printf("2.8: |%2.8c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("8.1: |%8.1c|", val));
	t = ft_printf(" (%d)\n", ft_printf("8.1: |%8.1c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("1.8: |%1.8c|", val));
	t = ft_printf(" (%d)\n", ft_printf("1.8: |%1.8c|", val));
	result(test, t);

	
	test = printf(" (%d)\n", printf("Handling precision & minimum field width & 0-flag"));
	t = ft_printf(" (%d)\n", ft_printf("Handling precision & minimum field width & 0-flag"));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) 00.0: |%00.0c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) 00.0: |%00.0c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) 01.0: |%01.0c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) 01.0: |%01.0c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) 00.1: |%00.1c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) 00.1: |%00.1c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("01.1: |%01.1c|", val));
	t = ft_printf(" (%d)\n", ft_printf("01.1: |%01.1c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("02.2: |%02.2c|", val));
	t = ft_printf(" (%d)\n", ft_printf("02.2: |%02.2c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("03.2: |%03.2c|", val));
	t = ft_printf(" (%d)\n", ft_printf("03.2: |%03.2c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("02.3: |%02.3c|", val));
	t = ft_printf(" (%d)\n", ft_printf("02.3: |%02.3c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("08.4: |%08.4c|", val));
	t = ft_printf(" (%d)\n", ft_printf("08.4: |%08.4c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("04.8: |%04.8c|", val));
	t = ft_printf(" (%d)\n", ft_printf("04.8: |%04.8c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("08.8: |%08.8c|", val));
	t = ft_printf(" (%d)\n", ft_printf("08.8: |%08.8c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("08.2: |%08.2c|", val));
	t = ft_printf(" (%d)\n", ft_printf("08.2: |%08.2c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("02.8: |%02.8c|", val));
	t = ft_printf(" (%d)\n", ft_printf("02.8: |%02.8c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("08.1: |%08.1c|", val));
	t = ft_printf(" (%d)\n", ft_printf("08.1: |%08.1c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("01.8: |%01.8c|", val));
	t = ft_printf(" (%d)\n", ft_printf("01.8: |%01.8c|", val));
	result(test, t);

	
	test = printf(" (%d)\n", printf("Handling minimum field width & 0-flag"));
	t = ft_printf(" (%d)\n", ft_printf("Handling minimum field width & 0-flag"));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) 0: |%0c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) 0: |%0c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) 00: |%00c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) 00: |%00c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) 01: |%01c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) 01: |%01c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) 02: |%02c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) 02: |%02c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("0: |%0c|", val));
	t = ft_printf(" (%d)\n", ft_printf("0: |%0c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("00: |%00c|", val));
	t = ft_printf(" (%d)\n", ft_printf("00: |%00c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("01: |%01c|", val));
	t = ft_printf(" (%d)\n", ft_printf("01: |%01c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("02: |%02c|", val));
	t = ft_printf(" (%d)\n", ft_printf("02: |%02c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("03: |%03c|", val));
	t = ft_printf(" (%d)\n", ft_printf("03: |%03c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("08: |%08c|", val));
	t = ft_printf(" (%d)\n", ft_printf("08: |%08c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("000000000008: |%000000000008c|", val));
	t = ft_printf(" (%d)\n", ft_printf("000000000008: |%000000000008c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("010: |%010c|", val));
	t = ft_printf(" (%d)\n", ft_printf("010: |%010c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("0000000000010: |%0000000000010c|", val));
	t = ft_printf(" (%d)\n", ft_printf("0000000000010: |%0000000000010c|", val));
	result(test, t);

	
	test = printf(" (%d)\n", printf("Handling minimum field width & 0-flag & '-' flag"));
	t = ft_printf(" (%d)\n", ft_printf("Handling minimum field width & 0-flag & '-' flag"));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) -0: |%-0c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) -0: |%-0c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) -00: |%-00c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) -00: |%-00c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) -01: |%-01c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) -01: |%-01c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) -02: |%-02c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) -02: |%-02c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("-0: |%-0c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-0: |%-0c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-00: |%-00c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-00: |%-00c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-01: |%-01c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-01: |%-01c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-02: |%-02c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-02: |%-02c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-03: |%-03c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-03: |%-03c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-08: |%-08c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-08: |%-08c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("0-8: |%0-8c|", val));
	t = ft_printf(" (%d)\n", ft_printf("0-8: |%0-8c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-000000000008: |%-000000000008c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-000000000008: |%-000000000008c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-010: |%-010c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-010: |%-010c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-0000000000010: |%-0000000000010c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-0000000000010: |%-0000000000010c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Handling minimum field width & left justification"));
	t = ft_printf(" (%d)\n", ft_printf("Handling minimum field width & left justification"));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) Mfw -0: |%-0c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) Mfw -0: |%-0c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) Mfw -1: |%-1c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) Mfw -1: |%-1c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) Mfw -2: |%-2c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) Mfw -2: |%-2c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw -0: |%-0c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw -0: |%-0c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw -1: |%-1c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw -1: |%-1c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw -2: |%-2c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw -2: |%-2c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw -3: |%-3c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw -3: |%-3c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw -4: |%-4c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw -4: |%-4c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw -5: |%-5c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw -5: |%-5c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw -10: |%-10c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw -10: |%-10c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw --10: |%--10c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw --10: |%--10c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw ---10: |%---10c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw ---10: |%---10c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw -15: |%-15c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw -15: |%-15c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw -42: |%-42c|", val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw -42: |%-42c|", val));
	result(test, t);

	test = printf(" (%d)\n", printf("Handling precision & minimum field width & left justification"));
	t = ft_printf(" (%d)\n", ft_printf("Handling precision & minimum field width & left justification"));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) -0.0: |%-0.0c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) -0.0: |%-0.0c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) -0.1: |%-0.1c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) -0.1: |%-0.1c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) -1.0: |%-1.0c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) -1.0: |%-1.0c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) -1.1: |%-1.1c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) -1.1: |%-1.1c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) -0.2: |%-0.2c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) -0.2: |%-0.2c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) -2.0: |%-2.0c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) -2.0: |%-2.0c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("(0) -2.2: |%-2.2c|", 0));
	t = ft_printf(" (%d)\n", ft_printf("(0) -2.2: |%-2.2c|", 0));
	result(test, t);
	test = printf(" (%d)\n", printf("-0.0: |%-0.0c|", 5));
	t = ft_printf(" (%d)\n", ft_printf("-0.0: |%-0.0c|", 5));
	result(test, t);
	test = printf(" (%d)\n", printf("-0.1: |%-0.1c|", 5));
	t = ft_printf(" (%d)\n", ft_printf("-0.1: |%-0.1c|", 5));
	result(test, t);
	test = printf(" (%d)\n", printf("-1.0: |%-1.0c|", 5));
	t = ft_printf(" (%d)\n", ft_printf("-1.0: |%-1.0c|", 5));
	result(test, t);
	test = printf(" (%d)\n", printf("-1.1: |%-1.1c|", 5));
	t = ft_printf(" (%d)\n", ft_printf("-1.1: |%-1.1c|", 5));
	result(test, t);
	test = printf(" (%d)\n", printf("-0.2: |%-0.2c|", 5));
	t = ft_printf(" (%d)\n", ft_printf("-0.2: |%-0.2c|", 5));
	result(test, t);
	test = printf(" (%d)\n", printf("-2.0: |%-2.0c|", 5));
	t = ft_printf(" (%d)\n", ft_printf("-2.0: |%-2.0c|", 5));
	result(test, t);
	test = printf(" (%d)\n", printf("-2.2: |%-2.2c|", 5));
	t = ft_printf(" (%d)\n", ft_printf("-2.2: |%-2.2c|", 5));
	result(test, t);
	test = printf(" (%d)\n", printf("-1.1: |%-1.1c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-1.1: |%-1.1c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-2.2: |%-2.2c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-2.2: |%-2.2c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-3.2: |%-3.2c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-3.2: |%-3.2c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-2.3: |%-2.3c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-2.3: |%-2.3c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-8.4: |%-8.4c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-8.4: |%-8.4c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-4.8: |%-4.8c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-4.8: |%-4.8c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-8.8: |%-8.8c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-8.8: |%-8.8c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-8.2: |%-8.2c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-8.2: |%-8.2c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-2.8: |%-2.8c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-2.8: |%-2.8c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-8.1: |%-8.1c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-8.1: |%-8.1c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-1.8: |%-1.8c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-1.8: |%-1.8c|", val));
	result(test, t);

	test = printf(" (%d)\n", printf("Handling wildcards"));
	t = ft_printf(" (%d)\n", ft_printf("Handling wildcards"));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw *1: |%*c|", 1, val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw *1: |%*c|", 1, val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw *5: |%*c|", 5, val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw *5: |%*c|", 5, val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw *5: |%*c|",5, val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw *5: |%*c|", 5, val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw *5: |%*c|",        5, val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw *5: |%*c|",        5, val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw *10: |%*c|", 10, val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw *10: |%*c|", 10, val));
	result(test, t);// 
	test = printf(" (%d)\n", printf("Mfw *i: |%*c|", val, val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw *i: |%*c|", val, val));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw **5: |%*.*c|", 5, 6, val));
	t = ft_printf(" (%d)\n", ft_printf("Mfw **5: |%*.*c|", 5, 6, val));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. .*1: |%.*c|", 1, val));
	t = ft_printf(" (%d)\n", ft_printf("Precis. .*1: |%.*c|", 1, val));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. .*5: |%.*c|", 5, val));
	t = ft_printf(" (%d)\n", ft_printf("Precis. .*5: |%.*c|", 5, val));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. .*5: |%.*c|",5, val));
	t = ft_printf(" (%d)\n", ft_printf("Precis. .*5: |%.*c|",5, val));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. .*5: |%.*c|",      5, val));
	t = ft_printf(" (%d)\n", ft_printf("Precis. .*5: |%.*c|",      5, val));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. .*10: |%.*c|", 10, val));
	t = ft_printf(" (%d)\n", ft_printf("Precis. .*10: |%.*c|", 10, val));
	result(test, t);// 
	test = printf(" (%d)\n", printf("Precis. .*i: |%.*c|", val, val));
	t = ft_printf(" (%d)\n", ft_printf("Precis. .*i: |%.*c|", val, val));
	result(test, t);
	test = printf(" (%d)\n", printf("P .*0: |%.*c|", 0, val));
	t = ft_printf(" (%d)\n", ft_printf("P .*0: |%.*c|", 0, val));
	result(test, t);
	test = printf(" (%d)\n", printf("P .*01: |%.*c|", 01, val));
	t = ft_printf(" (%d)\n", ft_printf("P .*01: |%.*c|", 01, val));
	result(test, t);
	test = printf(" (%d)\n", printf("P .*05: |%.*c|", 05, val));
	t = ft_printf(" (%d)\n", ft_printf("P .*05: |%.*c|", 05, val));
	result(test, t);
	test = printf(" (%d)\n", printf("P .*010: |%.*c|", 010, val));
	t = ft_printf(" (%d)\n", ft_printf("P .*010: |%.*c|", 010, val));
	result(test, t);
	test = printf(" (%d)\n", printf("P .*000000000007: |%.*c|", 000000000007, val));
	t = ft_printf(" (%d)\n", ft_printf("P .*000000000007: |%.*c|", 000000000007, val));
	result(test, t);
	test = printf(" (%d)\n", printf("*8.4: |%*.4c|", 8, val));
	t = ft_printf(" (%d)\n", ft_printf("*8.4: |%*.4c|", 8, val));
	result(test, t);
	test = printf(" (%d)\n", printf("*4.8: |%*.8c|", 4, val));
	t = ft_printf(" (%d)\n", ft_printf("*4.8: |%*.8c|", 4, val));
	result(test, t);
	test = printf(" (%d)\n", printf("*8.8: |%*.8c|", 8, val));
	t = ft_printf(" (%d)\n", ft_printf("*8.8: |%*.8c|", 8, val));
	result(test, t);
	test = printf(" (%d)\n", printf("8.*4: |%8.*c|", 4, val));
	t = ft_printf(" (%d)\n", ft_printf("8.*4: |%8.*c|", 4, val));
	result(test, t);
	test = printf(" (%d)\n", printf("4.*8: |%4.*c|", 8, val));
	t = ft_printf(" (%d)\n", ft_printf("4.*8: |%4.*c|", 8, val));
	result(test, t);
	test = printf(" (%d)\n", printf("8.*8: |%8.*c|", 8, val));
	t = ft_printf(" (%d)\n", ft_printf("8.*8: |%8.*c|", 8, val));
	result(test, t);
	test = printf(" (%d)\n", printf("*8.*4: |%*.*c|", 8, 4, val));
	t = ft_printf(" (%d)\n", ft_printf("*8.*4: |%*.*c|", 8, 4, val));
	result(test, t);
	test = printf(" (%d)\n", printf("*4.*8: |%*.*c|", 4, 8, val));
	t = ft_printf(" (%d)\n", ft_printf("*4.*8: |%*.*c|", 4, 8, val));
	result(test, t);
	test = printf(" (%d)\n", printf("*8.*8: |%*.*c|", 8, 8, val));
	t = ft_printf(" (%d)\n", ft_printf("*8.*8: |%*.*c|", 8, 8, val));
	result(test, t);
	printf("WEIRD OCTAL SHIT:\n");
	test = printf(" (%d)\n", printf("*010.*4: |%*.*c|", 010, 4, val));
	t = ft_printf(" (%d)\n", ft_printf("*010.*4: |%*.*c|", 010, 4, val));
	result(test, t);
	test = printf(" (%d)\n", printf(" *07.*4: |%*.*c|", 07, 4, val));
	t = ft_printf(" (%d)\n", ft_printf(" *07.*4: |%*.*c|", 07, 4, val));
	result(test, t);
	test = printf(" (%d)\n", printf("*4.*010: |%*.*c|", 4, 010, val));
	t = ft_printf(" (%d)\n", ft_printf("*4.*010: |%*.*c|", 4, 010, val));
	result(test, t);
	printf("WEIRD HEXADECIMAL SHIT:\n");
	test = printf(" (%d)\n", printf("*0x10.*4: |%*.*c|", 0x10, 4, val));
	t = ft_printf(" (%d)\n", ft_printf("*0x10.*4: |%*.*c|", 0x10, 4, val));
	result(test, t);
	test = printf(" (%d)\n", printf(" *0x7.*4: |%*.*c|", 0x7, 4, val));
	t = ft_printf(" (%d)\n", ft_printf(" *0x7.*4: |%*.*c|", 0x7, 4, val));
	result(test, t);
	test = printf(" (%d)\n", printf("*4.*0x10: |%*.*c|", 4, 0x10, val));
	t = ft_printf(" (%d)\n", ft_printf("*4.*0x10: |%*.*c|", 4, 0x10, val));
	result(test, t);
	test = printf(" (%d)\n", printf("*8: |%*c|", 8, val));
	t = ft_printf(" (%d)\n", ft_printf("*8: |%*c|", 8, val));
	result(test, t);
	test = printf(" (%d)\n", printf("0*8: |%0*c|", 8, val));
	t = ft_printf(" (%d)\n", ft_printf("0*8: |%0*c|", 8, val));
	result(test, t);
	test = printf(" (%d)\n", printf("00*8: |%00*c|", 8, val));
	t = ft_printf(" (%d)\n", ft_printf("00*8: |%00*c|", 8, val));
	result(test, t);

	
	test = printf(" (%d)\n", printf("00000000000000000*8: |%00000000000000000*c|", 8, val));
	t = ft_printf(" (%d)\n", ft_printf("00000000000000000*8: |%00000000000000000*c|", 8, val));
	result(test, t);
	test = printf(" (%d)\n", printf("-*0: |%-*c|", 0, val));
	t = ft_printf(" (%d)\n", ft_printf("-*0: |%-*c|", 0, val));
	result(test, t);
	test = printf(" (%d)\n", printf("-0*0: |%-0*c|", 0, val));
	t = ft_printf(" (%d)\n", ft_printf("-0*0: |%-0*c|", 0, val));
	result(test, t);
	test = printf(" (%d)\n", printf("-0*3: |%-0*c|", 3, val));
	t = ft_printf(" (%d)\n", ft_printf("-0*3: |%-0*c|", 3, val));
	result(test, t);
	test = printf(" (%d)\n", printf("*(-03): |%*c|", -03, val));
	t = ft_printf(" (%d)\n", ft_printf("*(-03): |%*c|", -03, val));
	result(test, t);
	test = printf(" (%d)\n", printf("*(-5): |%*c|", -5, val));
	t = ft_printf(" (%d)\n", ft_printf("*(-5): |%*c|", -5, val));
	result(test, t);
	test = printf(" (%d)\n", printf("*(5): |%*c|", 5, val));
	t = ft_printf(" (%d)\n", ft_printf("*(5): |%*c|", 5, val));
	result(test, t);
	test = printf(" (%d)\n", printf("-*(5): |%-*c|", 5, val));
	t = ft_printf(" (%d)\n", ft_printf("-*(5): |%-*c|", 5, val));
	result(test, t);
	test = printf(" (%d)\n", printf("-8.4: |%-8.4c|", val));
	t = ft_printf(" (%d)\n", ft_printf("-8.4: |%-8.4c|", val));
	result(test, t);
	test = printf(" (%d)\n", printf("-*(8).4: |%-*.4c|", 8, val));
	t = ft_printf(" (%d)\n", ft_printf("-*(8).4: |%-*.4c|", 8, val));
	result(test, t);
	test = printf(" (%d)\n", printf("*(-8).4: |%*.4c|", -8, val));
	t = ft_printf(" (%d)\n", ft_printf("*(-8).4: |%*.4c|", -8, val));
	result(test, t);
	test = printf(" (%d)\n", printf("*(int)(-8.4): |%*c|", ((int)(-8.4)), val));
	t = ft_printf(" (%d)\n", ft_printf("*(int)(-8.4): |%*c|", ((int)(-8.4)), val));
	result(test, t);
	test = printf(" (%d)\n", printf("-8.*(4): |%-8.*c|", 4, val));
	t = ft_printf(" (%d)\n", ft_printf("-8.*(4): |%-8.*c|", 4, val));
	result(test, t);
	test = printf(" (%d)\n", printf("-8.*(-4): |%-8.*c|", -4, val));
	t = ft_printf(" (%d)\n", ft_printf("-8.*(-4): |%-8.*c|", -4, val));
	result(test, t);
	test = printf(" (%d)\n", printf("-8.*(0): |%-8.*c|", 0, val));
	t = ft_printf(" (%d)\n", ft_printf("-8.*(0): |%-8.*c|", 0, val));
	result(test, t);
	test = printf(" (%d)\n", printf("-8.*(1): |%-8.*c|", 1, val));
	t = ft_printf(" (%d)\n", ft_printf("-8.*(1): |%-8.*c|", 1, val));
	result(test, t);
	test = printf(" (%d)\n", printf("-*(0).4: |%-*.4c|", 0, val));
	t = ft_printf(" (%d)\n", ft_printf("-*(0).4: |%-*.4c|", 0, val));
	result(test, t);
	test = printf(" (%d)\n", printf("*(0).4: |%*.4c|", 0, val));
	t = ft_printf(" (%d)\n", ft_printf("*(0).4: |%*.4c|", 0, val));
	result(test, t);

	
	test = printf(" (%d)\n", printf("Handling wildcards with 0 as input"));
	t = ft_printf(" (%d)\n", ft_printf("Handling wildcards with 0 as input"));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw *1: |%*c|", 1, 0));
	t = ft_printf(" (%d)\n", ft_printf("Mfw *1: |%*c|", 1, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw *5: |%*c|", 5, 0));
	t = ft_printf(" (%d)\n", ft_printf("Mfw *5: |%*c|", 5, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw *5: |%*c|",5, 0));
	t = ft_printf(" (%d)\n", ft_printf("Mfw *5: |%*c|", 5, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw *5: |%*c|",        5, 0));
	t = ft_printf(" (%d)\n", ft_printf("Mfw *5: |%*c|",        5, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw *10: |%*c|", 10, 0));
	t = ft_printf(" (%d)\n", ft_printf("Mfw *10: |%*c|", 10, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("Mfw *i: |%*c|", 0, 0));
	t = ft_printf(" (%d)\n", ft_printf("Mfw *i: |%*c|", 0, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. .*1: |%.*c|", 1, 0));
	t = ft_printf(" (%d)\n", ft_printf("Precis. .*1: |%.*c|", 1, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. .*5: |%.*c|", 5, 0));
	t = ft_printf(" (%d)\n", ft_printf("Precis. .*5: |%.*c|", 5, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. .*5: |%.*c|",5, 0));
	t = ft_printf(" (%d)\n", ft_printf("Precis. .*5: |%.*c|",5, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. .*5: |%.*c|",      5, 0));
	t = ft_printf(" (%d)\n", ft_printf("Precis. .*5: |%.*c|",      5, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. .*10: |%.*c|", 10, 0));
	t = ft_printf(" (%d)\n", ft_printf("Precis. .*10: |%.*c|", 10, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("Precis. .*i: |%.*c|", 0, 0));
	t = ft_printf(" (%d)\n", ft_printf("Precis. .*i: |%.*c|", 0, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("P .*0: |%.*c|", 0, 0));
	t = ft_printf(" (%d)\n", ft_printf("P .*0: |%.*c|", 0, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("P .*01: |%.*c|", 01, 0));
	t = ft_printf(" (%d)\n", ft_printf("P .*01: |%.*c|", 01, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("P .*05: |%.*c|", 05, 0));
	t = ft_printf(" (%d)\n", ft_printf("P .*05: |%.*c|", 05, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("P .*010: |%.*c|", 010, 0));
	t = ft_printf(" (%d)\n", ft_printf("P .*010: |%.*c|", 010, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("P .*000000000007: |%.*c|", 000000000007, 0));
	t = ft_printf(" (%d)\n", ft_printf("P .*000000000007: |%.*c|", 000000000007, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("*8.4: |%*.4c|", 8, 0));
	t = ft_printf(" (%d)\n", ft_printf("*8.4: |%*.4c|", 8, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("*4.8: |%*.8c|", 4, 0));
	t = ft_printf(" (%d)\n", ft_printf("*4.8: |%*.8c|", 4, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("*8.8: |%*.8c|", 8, 0));
	t = ft_printf(" (%d)\n", ft_printf("*8.8: |%*.8c|", 8, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("8.*4: |%8.*c|", 4, 0));
	t = ft_printf(" (%d)\n", ft_printf("8.*4: |%8.*c|", 4, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("4.*8: |%4.*c|", 8, 0));
	t = ft_printf(" (%d)\n", ft_printf("4.*8: |%4.*c|", 8, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("8.*8: |%8.*c|", 8, 0));
	t = ft_printf(" (%d)\n", ft_printf("8.*8: |%8.*c|", 8, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("*8.*4: |%*.*c|", 8, 4, 0));
	t = ft_printf(" (%d)\n", ft_printf("*8.*4: |%*.*c|", 8, 4, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("*4.*8: |%*.*c|", 4, 8, 0));
	t = ft_printf(" (%d)\n", ft_printf("*4.*8: |%*.*c|", 4, 8, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("*8.*8: |%*.*c|", 8, 8, 0));
	t = ft_printf(" (%d)\n", ft_printf("*8.*8: |%*.*c|", 8, 8, 0));
	result(test, t);
	printf("WEIRD OCTAL SHIT:\n");
	test = printf(" (%d)\n", printf("*010.*4: |%*.*c|", 010, 4, 0));
	t = ft_printf(" (%d)\n", ft_printf("*010.*4: |%*.*c|", 010, 4, 0));
	result(test, t);
	test = printf(" (%d)\n", printf(" *07.*4: |%*.*c|", 07, 4, 0));
	t = ft_printf(" (%d)\n", ft_printf(" *07.*4: |%*.*c|", 07, 4, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("*4.*010: |%*.*c|", 4, 010, 0));
	t = ft_printf(" (%d)\n", ft_printf("*4.*010: |%*.*c|", 4, 010, 0));
	result(test, t);
	printf("WEIRD HEXADECIMAL SHIT:\n");
	test = printf(" (%d)\n", printf("*0x10.*4: |%*.*c|", 0x10, 4, 0));
	t = ft_printf(" (%d)\n", ft_printf("*0x10.*4: |%*.*c|", 0x10, 4, 0));
	result(test, t);
	test = printf(" (%d)\n", printf(" *0x7.*4: |%*.*c|", 0x7, 4, 0));
	t = ft_printf(" (%d)\n", ft_printf(" *0x7.*4: |%*.*c|", 0x7, 4, 0));
	result(test, t);
	test = printf(" (%d)\n", printf("*4.*0x10: |%*.*c|", 4, 0x10, 0));
	t = ft_printf(" (%d)\n", ft_printf("*4.*0x10: |%*.*c|", 4, 0x10, 0));
	result(test, t);

	printf("		\x1b[31m FAILS: %d \x1b[0m\n\n\n", g_fail);

}
